services:
  django:
    container_name: housegallery_local_django
    image: housegallery_local_django
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ../.
      dockerfile: ./compose/django/Dockerfile
      args:
        - django_settings=config.settings.local
        - cloud_project=housegallery
        - build_type=dev-${LOCAL_ENV}
    volumes:
      - ..:/app:z
      - ~/.config/gcloud/application_default_credentials.json:/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - USE_CLOUD_DB=false
    ports:
      - '8000:8000'
    command: /start

  postgres:
    container_name: housegallery_local_postgres
    image: postgres:14
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/credentials.json
      - housegallery_postgres_data:/var/lib/postgresql/data
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - POSTGRES_DB=housegallery-dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

  node:
    container_name: housegallery_local_node
    platform: linux/amd64
    image: housegallery_local_node
    depends_on:
      - django
    build:
      context: ../.
      dockerfile: ./compose/node/Dockerfile
    volumes:
      - ..:/app:z
      - housegallery_local_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev

volumes:
  housegallery_local_node_modules:
  housegallery_postgres_data:
